# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: traffic-pod-autoscaler-cm
#   namespace: webapp
#   labels:
#     app.kubernetes.io/name: traffic-pod-autoscaler-cm
# data:
#   target-kind: "replica_set"
#   log-level: error
