apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-pod-autoscaler
  namespace: webapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traffic-pod-autoscaler
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traffic-pod-autoscaler
    spec:
      serviceAccountName: traffic-pod-autoscaler-sa
      containers:
      - name: traffic-pod-autoscaler
        image: ops-club/traffic_pod_autoscaler:latest
        imagePullPolicy: Never
        args:
        - --namespace=webapp
        - --local-port=9000
        - --deployment=frontend
        - --replica-set=frontend
        - --target-kind=replica_set
        - --config-map=traffic-pod-autoscaler-cm
        - --endpoint=frontend-svc
        - --target-address=frontend-svc
        - --target-port=80
        - --expiration-time=60
        - --check-interval=30
        - --log-level=DEBUG
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9000
